### DISCUSSION TITLE
Removendo '#' da url em site flutter

### DISCUSSION THREAD

**Discussion by CadisRaziel** [Flutterando/forum#60] [Dicas]
Nas dependencias do 'pubspec.yaml' adicione `flutter_web_plugins` é um plugin do próprio flutter: 
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
```

em seguida na **main**, adicione essa linha de código `setUrlStrategy(PathUrlStrategy());` :
```dart
void main() {
  setUrlStrategy(PathUrlStrategy());
  runApp(MyApp());
}
```
e prontinho..
